## Standing Ovation Problem

This is a very rough model on the Standing Ovation Problem.
The purpose is to have a quick and dirty idea on how the model could be implemented.
The code is not yet refined and may require revision and optimization.

#### A quick simulation of a rough model

In [271]:
import numpy as np

#### venue parameters

In [272]:
# assume theather is rectangular
nrows = 16
ncols = 12
nguests = nrows * ncols

#### guest as influencer parameters

In [273]:
# guests as influencer (Active)- ability to influence persons beside him/her
active_influence_factor = np.random.random((nrows, ncols)) 
active_influence_factor

array([[0.8516399 , 0.22368267, 0.2913378 , 0.46818773, 0.55907563,
        0.85331226, 0.94620391, 0.40320701, 0.17118403, 0.69289056,
        0.02818124, 0.09166342],
       [0.21517489, 0.08034373, 0.32166343, 0.09937941, 0.89119295,
        0.19227674, 0.60699579, 0.96293454, 0.75210713, 0.94955482,
        0.04807124, 0.65276859],
       [0.24809006, 0.89383296, 0.71194241, 0.28179696, 0.56216938,
        0.82388313, 0.7876907 , 0.88318267, 0.25514266, 0.36222265,
        0.09551254, 0.63591462],
       [0.1794037 , 0.68260244, 0.96239513, 0.7249737 , 0.02261087,
        0.02765403, 0.46067635, 0.57114398, 0.76757746, 0.14592382,
        0.6967832 , 0.23649344],
       [0.41667507, 0.38312624, 0.67876084, 0.57587922, 0.1317673 ,
        0.45906357, 0.33079463, 0.51162828, 0.43773908, 0.53527065,
        0.56384774, 0.07162442],
       [0.2213747 , 0.5890172 , 0.85189804, 0.32579601, 0.47735565,
        0.19868844, 0.23148155, 0.13540315, 0.59272066, 0.7488616 ,
        0.53917193,

#### guests as influenced (Passive)


In [274]:
# A person stands if performance is greater the his PPT
passive_performance_threshold = 0.6 + 0.4 * np.random.random((nrows, ncols))

In [275]:
# A person stands if a person *adjacent* to him has a PPT higher than his PIT
passive_adjacent_guest_influence_threshold = np.random.random((nrows, ncols))

In [276]:
# A person stands if number of persons around him stand (assume at least 2) 
passive_adjacent_guests_number_threshold = np.random.randint(2, 6,(nrows, ncols))
passive_adjacent_guests_number_threshold

array([[5, 4, 2, 4, 2, 2, 4, 2, 5, 3, 4, 5],
       [4, 2, 4, 4, 3, 2, 5, 5, 2, 2, 4, 3],
       [3, 2, 4, 5, 2, 3, 2, 5, 5, 5, 3, 5],
       [2, 4, 2, 5, 3, 5, 2, 4, 2, 2, 3, 5],
       [3, 2, 5, 2, 5, 3, 3, 2, 5, 3, 2, 4],
       [4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2],
       [4, 3, 3, 5, 4, 5, 4, 5, 2, 4, 3, 2],
       [2, 4, 3, 4, 3, 4, 3, 2, 2, 4, 4, 3],
       [5, 5, 5, 2, 3, 3, 5, 3, 2, 5, 5, 3],
       [2, 5, 5, 5, 2, 4, 4, 2, 2, 5, 4, 5],
       [3, 2, 2, 4, 3, 5, 4, 3, 5, 5, 5, 3],
       [5, 2, 4, 4, 5, 2, 4, 3, 2, 5, 5, 5],
       [4, 2, 4, 3, 2, 5, 5, 2, 4, 2, 3, 5],
       [3, 4, 5, 4, 3, 5, 3, 3, 5, 2, 4, 5],
       [5, 2, 2, 4, 2, 4, 4, 3, 2, 4, 4, 2],
       [4, 2, 4, 4, 5, 5, 4, 5, 3, 4, 3, 2]])

In [280]:
# A person stands if at least 33% of the number of persons in the rows in front of him stands 
passive_visible_guests_threshold = np.zeros(ncols)
for row in np.arange(1, nrows):
    frontrows_size = row*ncols
    v = np.random.randint(frontrows_size//3, frontrows_size, ncols)
    passive_visible_guests_threshold = np.vstack((passive_visible_guests_threshold, v))
passive_visible_guests_threshold

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [ 10.,  10.,  11.,   9.,   5.,   5.,   9.,   6.,   8.,   8.,   9.,
          8.],
       [ 18.,  23.,  14.,  13.,  16.,   8.,  21.,  18.,  13.,  20.,  15.,
         19.],
       [ 21.,  19.,  24.,  22.,  12.,  22.,  20.,  32.,  30.,  13.,  23.,
         23.],
       [ 23.,  32.,  25.,  29.,  46.,  28.,  21.,  26.,  18.,  19.,  42.,
         45.],
       [ 54.,  58.,  59.,  52.,  45.,  48.,  21.,  38.,  58.,  22.,  22.,
         58.],
       [ 67.,  37.,  32.,  43.,  47.,  67.,  58.,  33.,  67.,  49.,  32.,
         59.],
       [ 40.,  59.,  75.,  71.,  54.,  45.,  30.,  69.,  64.,  51.,  32.,
         76.],
       [ 65.,  65.,  56.,  75.,  82.,  81.,  51.,  89.,  51.,  32.,  48.,
         88.],
       [ 95.,  83., 101.,  36.,  99.,  48.,  60.,  83.,  80.,  73.,  54.,
         82.],
       [ 57., 110., 104., 108.,  81., 119.,  49.,  60., 100.,  81.,  86.,
         47.],
       [ 61.,  67.,  

In [290]:
# A person stands if number of persons in the room is at least 50%
passive_all_guests_threshold = np.random.randint(nguests//2, nguests, (nrows, ncols))
passive_all_guests_threshold

array([[156, 163, 111, 126, 185, 180, 100, 179, 136, 135, 118, 190],
       [106, 121, 114, 132, 137, 148, 137, 159, 102, 137,  97, 115],
       [128, 116, 150, 104, 175, 170, 104, 105, 186, 129, 156, 146],
       [142, 174, 150, 113, 147, 110, 113, 113, 169, 143, 190,  98],
       [133, 126, 106, 153, 165, 159, 105, 118, 149, 158, 113, 154],
       [175, 112, 128, 155, 183, 172, 111, 173, 145, 132, 104, 163],
       [146, 105, 122,  98,  98, 173, 100, 105, 132, 169, 183, 146],
       [189, 189, 141, 176, 137, 190, 116, 152, 128, 189, 133, 160],
       [187, 182, 118,  98, 162, 159, 111, 112, 183, 138, 136, 171],
       [178, 101, 183, 175, 171, 146, 184, 149, 181, 165, 120, 148],
       [134, 133, 106, 122, 178, 184, 133, 167, 114, 171, 181, 176],
       [154, 100, 144, 150, 139, 100, 186, 182, 132, 148, 112, 139],
       [180, 168, 129, 126, 185, 128, 138, 144, 181, 191, 141, 111],
       [111, 170, 109,  98, 165, 107, 108, 109, 120, 159,  96, 137],
       [190, 176, 108, 155, 169, 1

#### time parameters

In [282]:
# how long a person is willing to stand
hold = np.random.randint(1, num_iter//3, (nrows, ncols))
hold

array([[5, 3, 1, 1, 2, 4, 2, 3, 3, 1, 3, 1],
       [5, 3, 5, 2, 1, 1, 1, 1, 4, 3, 1, 5],
       [1, 2, 3, 1, 5, 1, 5, 4, 1, 3, 2, 1],
       [2, 4, 4, 4, 2, 1, 3, 5, 3, 2, 1, 3],
       [2, 1, 2, 4, 1, 4, 1, 5, 3, 2, 4, 5],
       [2, 1, 3, 1, 4, 2, 1, 3, 4, 4, 2, 2],
       [1, 1, 4, 2, 4, 4, 5, 4, 1, 1, 2, 3],
       [4, 5, 3, 3, 5, 1, 5, 5, 5, 4, 3, 5],
       [1, 3, 1, 2, 3, 3, 3, 4, 3, 5, 3, 5],
       [2, 5, 3, 5, 4, 5, 2, 3, 4, 4, 2, 3],
       [4, 1, 3, 5, 1, 2, 4, 4, 4, 3, 4, 3],
       [5, 3, 3, 2, 5, 1, 1, 3, 4, 2, 1, 4],
       [4, 2, 3, 1, 4, 1, 2, 4, 1, 1, 1, 4],
       [5, 1, 4, 4, 5, 2, 1, 2, 3, 2, 5, 3],
       [2, 2, 1, 3, 4, 4, 3, 5, 5, 2, 3, 1],
       [2, 3, 1, 2, 1, 3, 2, 3, 4, 4, 3, 1]])

### Simulation

In [283]:
def adjacent_influenced(s, i, j):
    # seat to the left of the guest
    if (j>1) and s[i, j-1] and (active_influence_factor[i, j-1] > passive_adjacent_guest_influence_threshold[i, j]):
        return True 
    # seat to the right of the guest
    if (j<(ncols-1)) and s[i, j+1] and (active_influence_factor [i, j+1] > passive_adjacent_guest_influence_threshold[i, j]):
        return True
    return False

In [284]:
def S(s, row, col):
    """return the value of s[row, col] if indices are within bounds.
       otherwise, return 0
    """
    if row>=0 and row<nrows:
        if col>=0 and col<ncols:
            return s[row, col]
    return 0

In [285]:
def persons_around_influenced(s, i, j):
    num_standing = S(s, i-1, j-1) + S(s, i-1, j) + S(s, i-1, j+1) + S(s, i, j+1)  + S(s, i, j-1) 
    if num_standing > passive_adjacent_guests_number_threshold[i, j]:
        return True
    return False
 

In [286]:
def visible_guests_influenced(s, i, j):
    num_standing = 0
    for row in range (i):# rows before i
        num_standing = standing[i].sum()
    if num_standing > passive_visible_guests_threshold[i, j]:
        return True
    return False

In [287]:
def all_guests_influenced(s, i, j):
    num_standing = s.sum()
    if num_standing > passive_all_guests_threshold[i, j]:
        return True
    return False    

#### performance parameters

In [288]:
# can also be set randomly via np.random.random()
performance_quality = 0.8 

#### Loop through all guests for num_iter times

In [289]:
num_iter = 20
standing = np.zeros((nrows, ncols))
for t in range(num_iter):
    new_standing = standing
    for i in range(nrows):
        for j in range(ncols):
            if standing[i, j]:
                if t>hold[i, j]:
                    new_standing[i, j] = 0
            else:
                if performance_quality > passive_performance_threshold[i, j]:
                    new_standing[i, j] = 1
                elif adjacent_influenced(standing, i, j):
                    new_standing[i, j] = 1
                elif persons_around_influenced(standing, i, j):
                    new_standing[i, j] = 1
                elif visible_guests_influenced(standing, i, j):
                    new_standing[i, j] = 1
                elif all_guests_influenced(standing, i, j):
                    new_standing[i, j] = 1
    standing = new_standing
    print(f'Iteration: {t+1}')
    print(f'No.Persons Standing: {int(standing.sum())}')
    print(f'Percentage Standing: {100*standing.sum()/nguests:.0f}%')    
    #print(standing)

Iteration: 1
No.Persons Standing: 132
Percentage Standing: 69%
Iteration: 2
No.Persons Standing: 187
Percentage Standing: 97%
Iteration: 3
No.Persons Standing: 145
Percentage Standing: 76%
Iteration: 4
No.Persons Standing: 154
Percentage Standing: 80%
Iteration: 5
No.Persons Standing: 97
Percentage Standing: 51%
Iteration: 6
No.Persons Standing: 94
Percentage Standing: 49%
Iteration: 7
No.Persons Standing: 48
Percentage Standing: 25%
Iteration: 8
No.Persons Standing: 93
Percentage Standing: 48%
Iteration: 9
No.Persons Standing: 58
Percentage Standing: 30%
Iteration: 10
No.Persons Standing: 95
Percentage Standing: 49%
Iteration: 11
No.Persons Standing: 58
Percentage Standing: 30%
Iteration: 12
No.Persons Standing: 95
Percentage Standing: 49%
Iteration: 13
No.Persons Standing: 58
Percentage Standing: 30%
Iteration: 14
No.Persons Standing: 95
Percentage Standing: 49%
Iteration: 15
No.Persons Standing: 58
Percentage Standing: 30%
Iteration: 16
No.Persons Standing: 95
Percentage Standing: 4